apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: data
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auth
  name: auth
  namespace: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth
    spec:
      containers:
      - image: cmwylie19/auth:0.0.1
        command: ["./auth", "serve"]
        name: auth
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: auth
  name: auth
  namespace: data
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31469
  selector:
    app: auth
  type: NodePort
status:
  loadBalancer: {}
